# Generated by Django 6.1 on 2026-09-21 18:40

from django.db import migrations, models


def backfill_scan_state(apps, schema_editor):
    """Existing invoices were scanned inline at upload, so none of them are
    waiting for anything. Left at the QUEUED default they would look to the
    app like uploads still being read, and a worker would re-read every
    invoice ever uploaded.
    """
    InvoiceScan = apps.get_model("inventory", "InvoiceScan")
    InvoiceScan.objects.exclude(scan_error="").update(scan_state="FAILED")
    InvoiceScan.objects.filter(scan_error="").update(scan_state="DONE")


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicescan",
            name="scan_state",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Waiting to be read"),
                    ("SCANNING", "Being read"),
                    ("DONE", "Read"),
                    ("FAILED", "Could not be read"),
                ],
                default="QUEUED",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_scan_state, migrations.RunPython.noop),
    ]
