# Generated by Django 6.1 on 2026-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_invoicescan_scan_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescan',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoicescan',
            name='photo',
            field=models.FileField(upload_to='invoice_scans/'),
        ),
    ]
