# Generated by Django 6.1 on 2026-09-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_invoicescan_content_type_alter_invoicescan_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicescan',
            name='scan_state',
            field=models.CharField(choices=[('AWAITING_UPLOAD', 'Waiting for the file'), ('QUEUED', 'Waiting to be read'), ('SCANNING', 'Being read'), ('DONE', 'Read'), ('FAILED', 'Could not be read')], default='QUEUED', max_length=16),
        ),
    ]
