# Generated by Django 6.1 on 2026-09-21 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_suppliers(apps, schema_editor):
    """Turn the supplier names already read off invoices into real rows.

    Every invoice so far carries a free-text supplier_name and nothing else.
    Left alone, the supplier list would start empty while historical invoices
    all read "Fresh Foods Ltd" and matched nothing - so a restaurant's own
    past would be invisible to the very filters this migration exists to
    enable.

    Unlike scanning, doing this here is safe: these names were shown to a
    person who reviewed and kept the invoice, and the normalized key collapses
    the spelling variants that made them look like different suppliers.
    """
    InvoiceScan = apps.get_model("inventory", "InvoiceScan")
    Supplier = apps.get_model("inventory", "Supplier")

    # Imported rather than redefined: a backfill that normalizes differently
    # from the matcher creates rows the matcher will never find again.
    from apps.inventory.models.suppliers import normalize_supplier_name

    seen: dict[tuple, object] = {}
    for invoice in InvoiceScan.objects.exclude(supplier_name="").iterator():
        normalized = normalize_supplier_name(invoice.supplier_name)
        if not normalized:
            continue

        key = (invoice.restaurant_id, normalized)
        supplier = seen.get(key)
        if supplier is None:
            supplier, _ = Supplier.objects.get_or_create(
                restaurant_id=invoice.restaurant_id,
                normalized_name=normalized,
                defaults={"name": invoice.supplier_name.strip()},
            )
            seen[key] = supplier

        InvoiceScan.objects.filter(pk=invoice.pk).update(supplier=supplier)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_invoicescan_scan_state'),
        ('restaurants', '0002_restaurant_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(editable=False, max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='invoicescan',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.supplier'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='invoicescan',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('restaurant', 'normalized_name'), name='unique_supplier_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_warehouse_name_per_restaurant'),
        ),
        migrations.RunPython(backfill_suppliers, migrations.RunPython.noop),
    ]
