# Generated by Django 6.1 on 2026-09-21 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_supplier_and_warehouse'),
        ('restaurants', '0002_restaurant_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('normalized_text', models.CharField(editable=False, max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.inventoryitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_aliases', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('text',),
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'normalized_text'), name='unique_item_alias_per_restaurant')],
            },
        ),
    ]
