# Generated by Django 6.1 on 2026-09-21 19:38

from django.db import migrations, models


def backfill_normalized_names(apps, schema_editor):
    """Fill the new column before anything unique is asked of it.

    The field lands defaulting to "", so every existing warehouse would share
    that value and the unique constraint below would refuse to build the
    moment a restaurant has two of them. The migration has to run in this
    order: add, fill, then constrain.
    """
    Warehouse = apps.get_model("inventory", "Warehouse")

    # Imported rather than copied: a backfill that normalizes differently from
    # the model would write keys the matcher can never find again.
    from apps.inventory.models.warehouses import normalize_warehouse_name

    for warehouse in Warehouse.objects.all().iterator():
        Warehouse.objects.filter(pk=warehouse.pk).update(
            normalized_name=normalize_warehouse_name(warehouse.name)
        )


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_invoice_stated_figures"),
        ("restaurants", "0002_restaurant_approval"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="warehouse",
            name="unique_warehouse_name_per_restaurant",
        ),
        migrations.AddField(
            model_name="warehouse",
            name="normalized_name",
            field=models.CharField(default="", editable=False, max_length=120),
        ),
        migrations.RunPython(backfill_normalized_names, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "normalized_name"),
                name="unique_warehouse_name_per_restaurant",
            ),
        ),
    ]
