# Generated by Django 6.1 on 2026-09-21 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_warehouse_normalized_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescan',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='inventory.invoicescan'),
        ),
        migrations.AddField(
            model_name='invoicescan',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='invoicescan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending review'), ('CONFIRMED', 'Confirmed'), ('DISCARDED', 'Discarded'), ('DUPLICATE', 'Duplicate upload')], default='PENDING', max_length=16),
        ),
    ]
