# Generated by Django 6.1 on 2026-09-21 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_duplicate_detection'),
        ('restaurants', '0002_restaurant_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanUsage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('scans', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_usage', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('-month',),
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'month'), name='unique_scan_usage_per_month')],
            },
        ),
    ]
