# Generated by Django 6.1 on 2026-09-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_scan_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicescan',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit note')], default='INVOICE', max_length=16),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('DELIVERY', 'Delivery received'), ('WASTE', 'Waste / spoilage'), ('CORRECTION', 'Manual correction'), ('RETURN', 'Returned / credited')], max_length=16),
        ),
    ]
