# Generated by Django 6.1 on 2026-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="job_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHEF", "Chef"),
                    ("DRIVER", "Driver"),
                    ("TILL_OPERATOR", "Till operator"),
                ],
                max_length=16,
            ),
        ),
    ]
