# Generated by Django 6.1 on 2026-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_shift_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
