# Generated by Django 6.1 on 2026-09-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancelog_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
