# Generated by Django 6.1 on 2026-09-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('SHIFT_REMINDER', 'Shift reminder'), ('SHIFT_ADDED', 'Shift added'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_CANCELLED', 'Shift cancelled'), ('MISSED_CHECKOUT', 'Missed checkout'), ('COMPLIANCE_OVERDUE', 'Compliance overdue')], max_length=32),
        ),
    ]
