# Generated by Django 6.1 on 2026-09-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('SHIFT_REMINDER', 'Shift reminder'), ('SHIFT_ENDING_SOON', 'Shift ending soon'), ('SHIFT_ADDED', 'Shift added'), ('SHIFT_UPDATED', 'Shift updated'), ('SHIFT_CANCELLED', 'Shift cancelled'), ('STAFF_CHECKED_IN', 'Staff checked in'), ('STAFF_CHECKED_OUT', 'Staff checked out'), ('MISSED_CHECKOUT', 'Missed checkout'), ('COMPLIANCE_OVERDUE', 'Compliance overdue')], max_length=32),
        ),
    ]
