# Generated by Django 6.1 on 2026-09-03 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_restaurants(apps, schema_editor):
    """Approval is a gate on the new public self-registration path (see
    RegisterSerializer) - restaurants that already existed before this
    migration were not created through it, so backfill them as approved
    rather than retroactively locking every current tenant out."""
    Restaurant = apps.get_model("restaurants", "Restaurant")
    Restaurant.objects.update(is_approved=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(approve_existing_restaurants, noop),
    ]
