# Generated by Django 6.1 on 2026-09-18 01:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_restaurant_approval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('routine', models.CharField(choices=[('OPENING', 'Opening'), ('CLOSING', 'Closing')], max_length=16)),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('routine', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='FridgeUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('FRIDGE', 'Fridge'), ('FREEZER', 'Freezer')], default='FRIDGE', max_length=16)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fridge_units/')),
                ('recommended_max_celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridge_units', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistCompletion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_completions', to='restaurants.restaurant')),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='compliance.checklistitem')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('checklist_item', 'date'), name='one_completion_per_item_per_day')],
            },
        ),
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('routine', models.CharField(choices=[('OPENING', 'Opening'), ('CLOSING', 'Closing')], max_length=16)),
                ('date', models.DateField()),
                ('celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('fridge_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='compliance.fridgeunit')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_readings', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ('-date',),
                'constraints': [models.UniqueConstraint(fields=('fridge_unit', 'routine', 'date'), name='one_reading_per_fridge_routine_day')],
            },
        ),
    ]
