# Generated by Django 6.1 on 2026-09-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_checklisttemplate_checklisttask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistcompletion',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='checklisttaskcompletion',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='temperaturereading',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
